name: Recipe for Banana Bread
title: Recipe for Banana Bread | A blog theme for Jekyll
description: Recipe for Banana Bread is a template for Jekyll inspired by Netflix and made by
  .
tags:
  - blog
  - template
  - jekyll
  - theme
  - netlify
show_hero: true
menu:
  - title: Home
    url: /
  - title: About
    url: /about
  - title: Contact
    url: /contact
  - title: Feed
    url: /feed.xml
email: youremail@test.com
# See: https://disqus.com/
disqus_username: disqus_username
# Contact Form Setting
# See: https://formspree.io/
formspree_form_id: formspree_form_id
